### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/tomcat/util/res/StringManager

### ISSUE THREAD

**Issue by krazyito65** [web-servers/tomcat-vault#64]
```
$ java -classpath tomcat-vault-1.1.7.Final-jar-with-dependencies.jar org.apache.tomcat.vault.VaultTool
Please enter a Digit::   0: Start Interactive Session  1: Remove Interactive Session  Other: Exit
0
Starting an interactive session
Enter directory to store encrypted files:/tmp/vault/
Enter Keystore URL:/tmp/vault/vault.keystore
Enter Keystore password: 
Enter Keystore password again: 
Values match
Enter 8 character salt:1234abcd
Enter iteration count as a number (Eg: 44):44
Enter Keystore Alias:my_vault
Initializing Vault
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/tomcat/util/res/StringManager
        at org.apache.tomcat.vault.security.plugins.PBEUtils.<clinit>(PBEUtils.java:49)
        at org.apache.tomcat.vault.VaultSession.computeMaskedPassword(VaultSession.java:161)
        at org.apache.tomcat.vault.VaultSession.startVaultSession(VaultSession.java:191)
        at org.apache.tomcat.vault.VaultInteractiveSession.start(VaultInteractiveSession.java:77)
        at org.apache.tomcat.vault.VaultTool.main(VaultTool.java:123)
Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.util.res.StringManager
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        ... 5 more
```

Using version 1.1.7 I'm getting this error when trying to run it in interactive mode for testing.

I am using Java 6 and Tomcat 6, but I can up the version of java no problem.  This particular error seems to be the same regardless of java 6-8

**Comment by krazyito65** [comment]
Figured it out... it was my own issue.  Just had to add some more tomcat jars to the classpath

`tomcat-vault-1.1.7.Final-jar-with-dependencies.jar:tomcat-coyote.jar:tomcat-juli.jar`
